const projects = [
	{
		id: 1,
		category: "web",
		icon: "fas fa-globe",
		name: "Quranium Main Website",
		tech: "Next.js, Tailwind CSS, Axios, SEO",
		title: "Quranium Main Website",
		catLabel: "Web Development",
		colorClass: "portfolio-item-1",
        link: "https://quranium.org",
	},
	{
		id: 2,
		category: "web",
		icon: "fas fa-search",
		name: "QRNScan Blockchain Explorer",
		tech: "Next.js, Tailwind CSS, Axios, Blockchain APIs",
		title: "QRNScan",
		catLabel: "Web Development",
		colorClass: "portfolio-item-2",
        link: "https://qrnscan.com",
	},
	{
		id: 3,
		category: "web",
		icon: "fas fa-share-alt",
		name: "SocialFi Platform",
		tech: "Next.js, Tailwind CSS, Axios",
		title: "SocialFi",
		catLabel: "Web Development",
		colorClass: "portfolio-item-3",
        link: "https://community.quranium.org",
	},
	{
		id: 4,
		category: "web",
		icon: "fas fa-wallet",
		name: "Q-Safe Wallet Extension",
		tech: "Vue.js, Web3, Smart Contracts",
		title: "Q-Safe Wallet",
		catLabel: "Web3 Development",
		colorClass: "portfolio-item-4",
        link: "https://chromewebstore.google.com/detail/opnnmgopaggjpapnoknbphfpjfadbddc?utm_source=item-share-cb",
	},
	{
		id: 5,
		category: "app",
		icon: "fas fa-mobile-alt",
		name: "QINFI Super App",
		tech: "React Native, NestJS, TypeORM, Blockchain RPC",
		title: "QINFI",
		catLabel: "App Development",
		colorClass: "portfolio-item-5",
        link: "",
	},
	{
		id: 6,
		category: "app",
		icon: "fas fa-tools",
		name: "Subidha Services App",
		tech: "Flutter, Razorpay, Authentication",
		title: "Subidha",
		catLabel: "App Development",
		colorClass: "portfolio-item-6",
        link: "https://play.google.com/store/apps/details?id=com.mindstar.home_services",
	},
	{
		id: 7,
		category: "app",
		icon: "fas fa-comments",
		name: "Lyk Social Media App",
		tech: "Flutter, Cross-Platform UI",
		title: "Lyk",
		catLabel: "App Development",
		colorClass: "portfolio-item-7",
        link: "https://play.google.com/store/apps/details?id=com.mm.parentconcern",
	},
	{
		id: 8,
		category: "app",
		icon: "fas fa-taxi",
		name: "GoRide Cab Booking App",
		tech: "Flutter, Real-Time Booking",
		title: "GoRide",
		catLabel: "App Development",
		colorClass: "portfolio-item-8",
        link: "",
	},
	{
		id: 9,
		category: "web",
		icon: "fas fa-file-medical",
		name: "Prescription Generator Website",
		tech: "Next.js, TypeScript, Tailwind CSS, tRPC",
		title: "Prescription Generator",
		catLabel: "Web Development",
		colorClass: "portfolio-item-9",
        link: "https://prescription-generate-mu.vercel.app/",
	},
    {
		id: 10,
		category: "Others",
		icon: "fas fa-file-medical",
		name: "Lawgistics AI – Legal AI Platform",
		tech: "Next.js, TypeScript, Tailwind CSS, Nest.Js, OpenAI, Claude, Prisma",
		title: "Lawgistics AI – Legal AI Platform",
		catLabel: "Others",
		colorClass: "portfolio-item-9",
        link: "https://lawgisticsai.com/",
	},
    {
		id: 11,
		category: "Others",
		icon: "fas fa-file-medical",
		name: "DueDraft AI",
		tech: "Next.js, TypeScript, Tailwind CSS, Nest.Js, OpenAI, Claude, Prisma",
		title: "DueDraft AI",
		catLabel: "Others",
		colorClass: "portfolio-item-9",
        link: "https://duedraft.ai/",
	},
];

export default projects;